name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"
      
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: .venv
          key: ${{ runner.os }}-venv-${{ hashFiles('pyproject.toml') }}
          
      - name: Install dependencies
        run: |
          uv venv
          uv pip install -e .[dev]
          
      - name: Lint with ruff
        run: |
          ruff check .
          ruff format --check .
          
      - name: Run tests
        run: |
          pytest --cov=app --cov-report=term-missing --cov-fail-under=80
